# big query logger shared configuration
bigquery_log:
  template: "%Y%m%d%H"
  format: >-
    {
    \"service_id\":\"%{req.service_id}V\",
    \"time_start\":\"%{begin:%Y-%m-%dT%H:%M:%S%Z}t\",
    \"time_end\":\"%{end:%Y-%m-%dT%H:%M:%S%Z}t\",
    \"time_elapsed\":%D,
    \"client_ip\":\"%h\",
    \"client_as_name\":\"%{client.as.name}V\",
    \"client_as_number\":\"%{client.as.number}V\",
    \"client_connection_speed\":\"%{client.geo.conn_speed}V\",
    \"request\":\"%m\",
    \"protocol\":\"%H\",
    \"host\":\"%{Fastly-Orig-Host}i\",
    \"origin_host\":\"%v\",
    \"url\":\"%{json.escape(cstr_escape(regsub(req.url, \\\"^(.\\{0,2047\\}).*\\\", \\\"\\\\1\\\")))}V\",
    \"is_ipv6\":%{if(req.is_ipv6, \\\"true\\\", \\\"false\\\")}V,
    \"is_tls\":%{if(req.is_ssl, \\\"true\\\", \\\"false\\\")}V,
    \"tls_client_protocol\":\"%{cstr_escape(tls.client.protocol)}V\",
    \"tls_client_servername\":\"%{cstr_escape(tls.client.servername)}V\",
    \"tls_client_cipher\":\"%{cstr_escape(tls.client.cipher)}V\",
    \"tls_client_cipher_sha\":\"%{cstr_escape(tls.client.ciphers_sha)}V\",
    \"tls_client_tlsexts_sha\":\"%{cstr_escape(tls.client.tlsexts_sha)}V\",
    \"is_h2\":%{if(fastly_info.is_h2, \\\"true\\\", \\\"false\\\")}V,
    \"is_h2_push\":%{if(fastly_info.h2.is_push, \\\"true\\\", \\\"false\\\")}V,
    \"h2_stream_id\":\"%{fastly_info.h2.stream_id}V\",
    \"request_referer\":\"%{json.escape(req.http.Referer)}V\",
    \"request_user_agent\":\"%{json.escape(regsub(req.http.User-Agent, \\\"^(.\\{0,200\\}).*\\\", \\\"\\\\1\\\"))}V\",
    \"request_accept_content\":\"%{Accept}i\",
    \"request_accept_language\":\"%{Accept-Language}i\",
    \"request_accept_encoding\":\"%{Accept-Encoding}i\",
    \"request_accept_charset\":\"%{Accept-Charset}i\",
    \"request_connection\":\"%{Connection}i\",
    \"request_dnt\":\"%{DNT}i\",
    \"request_forwarded\":\"%{Forwarded}i\",
    \"request_via\":\"%{Via}i\",
    \"request_cache_control\":\"%{Cache-Control}i\",
    \"request_x_requested_with\":\"%{X-Requested-With}i\",
    \"request_x_att_device_id\":\"%{X-ATT-Device-Id}i\",
    \"request_x_forwarded_for\":\"%{X-Forwarded-For}i\",
    \"status\":\"%s\",
    \"content_type\":\"%{Content-Type}o\",
    \"cache_status\":\"%{fastly_info.state}V\",
    \"is_cacheable\":%{if(fastly_info.state ~\\\"^(HIT|MISS)$\\\", \\\"true\\\", \\\"false\\\")}V,
    \"response_age\":\"%{Age}o\",
    \"response_cache_control\":\"%{Cache-Control}o\",
    \"response_expires\":\"%{Expires}o\",
    \"response_last_modified\":\"%{Last-Modified}o\",
    \"response_tsv\":\"%{TSV}o\",
    \"server_datacenter\":\"%{server.datacenter}V\",
    \"server_ip\":\"%A\",
    \"geo_city\":\"%{client.geo.city.utf8}V\",
    \"geo_country_code\":\"%{client.geo.country_code}V\",
    \"geo_continent_code\":\"%{client.geo.continent_code}V\",
    \"geo_region\":\"%{client.geo.region}V\",
    \"req_header_size\":%{req.header_bytes_read}V,
    \"req_body_size\":%{req.body_bytes_read}V,
    \"resp_header_size\":%{resp.header_bytes_written}V,
    \"resp_body_size\":%B,
    \"socket_cwnd\":%{client.socket.cwnd}V,
    \"socket_nexthop\":\"%{client.socket.nexthop}V\",
    \"socket_tcpi_rcv_mss\":%{client.socket.tcpi_rcv_mss}V,
    \"socket_tcpi_snd_mss\":%{client.socket.tcpi_snd_mss}V,
    \"socket_tcpi_rtt\":%{client.socket.tcpi_rtt}V,
    \"socket_tcpi_rttvar\":%{client.socket.tcpi_rttvar}V,
    \"socket_tcpi_rcv_rtt\":%{client.socket.tcpi_rcv_rtt}V,
    \"socket_tcpi_rcv_space\":%{client.socket.tcpi_rcv_space}V,
    \"socket_tcpi_last_data_sent\":%{client.socket.tcpi_last_data_sent}V,
    \"socket_tcpi_total_retrans\":%{client.socket.tcpi_total_retrans}V,
    \"socket_tcpi_delta_retrans\":%{client.socket.tcpi_delta_retrans}V,
    \"socket_ploss\":%{client.socket.ploss}V,
    \"backend_name\":\"%{if(req.http.x-nyt-backend,req.http.x-nyt-backend,\\\"\\\")}V\",
    \"pagetype\":\"%{if(req.http.x-nyt-route,req.http.x-nyt-route,\\\"\\\")}V\",
    \"apiversion\":\"%{if(resp.http.X-API-Version,resp.http.X-API-Version,\\\"\\\")}V\",
    \"redirect_reason\":\"%{if(req.http.var-nyt-redirect-reason,regsub(req.http.var-nyt-redirect-reason,\\\"redir=\\\\[([^\\\\]]+)\\\\]\\\",\\\"\\\\1\\\"),\\\"\\\")}V\",
    \"trace_id\": \"%{if(req.http.x-b3-trace-id,req.http.x-b3-trace-id,\\\"\\\")}V\",
    \"backend_healthy\": \"%{if(req.http.x-nyt-backend-health,req.http.x-nyt-backend-health,\\\"\\\")}V\",
    \"restarts\": %{req.restarts}V,
    \"route\": \"%{if(req.http.x-nyt-route,req.http.x-nyt-route,\\\"\\\")}V\",
    \"is_shield\": %{if(req.http.x-nyt-shield-auth,\\\"true\\\",\\\"false\\\")}V,
    \"restart_reason\":\"%{if(req.http.x-nyt-restart-reason,req.http.x-nyt-restart-reason,\\\"\\\")}V\"
    }

# GCS logger shared configuration
gcslogging:
  format: >-
    {
    \"service_id\":\"%{req.service_id}V\",
    \"time_start\":\"%{begin:%Y-%m-%dT%H:%M:%S%Z}t\",
    \"time_end\":\"%{end:%Y-%m-%dT%H:%M:%S%Z}t\",
    \"time_elapsed\":%D,
    \"client_ip\":\"%h\",
    \"client_as_name\":\"%{client.as.name}V\",
    \"client_as_number\":\"%{client.as.number}V\",
    \"client_connection_speed\":\"%{client.geo.conn_speed}V\",
    \"request\":\"%m\",
    \"protocol\":\"%H\",
    \"host\":\"%{Fastly-Orig-Host}i\",
    \"origin_host\":\"%v\",
    \"url\":\"%{json.escape(cstr_escape(regsub(req.url, \\\"^(.\\{0,2047\\}).*\\\", \\\"\\\\1\\\")))}V\",
    \"is_ipv6\":%{if(req.is_ipv6, \\\"true\\\", \\\"false\\\")}V,
    \"is_tls\":%{if(req.is_ssl, \\\"true\\\", \\\"false\\\")}V,
    \"tls_client_protocol\":\"%{cstr_escape(tls.client.protocol)}V\",
    \"tls_client_servername\":\"%{cstr_escape(tls.client.servername)}V\",
    \"tls_client_cipher\":\"%{cstr_escape(tls.client.cipher)}V\",
    \"tls_client_cipher_sha\":\"%{cstr_escape(tls.client.ciphers_sha)}V\",
    \"tls_client_tlsexts_sha\":\"%{cstr_escape(tls.client.tlsexts_sha)}V\",
    \"is_h2\":%{if(fastly_info.is_h2, \\\"true\\\", \\\"false\\\")}V,
    \"is_h2_push\":%{if(fastly_info.h2.is_push, \\\"true\\\", \\\"false\\\")}V,
    \"h2_stream_id\":\"%{fastly_info.h2.stream_id}V\",
    \"request_referer\":\"%{json.escape(req.http.Referer)}V\",
    \"request_user_agent\":\"%{json.escape(regsub(req.http.User-Agent, \\\"^(.\\{0,200\\}).*\\\", \\\"\\\\1\\\"))}V\",
    \"request_accept_content\":\"%{Accept}i\",
    \"request_accept_language\":\"%{Accept-Language}i\",
    \"request_accept_encoding\":\"%{Accept-Encoding}i\",
    \"request_accept_charset\":\"%{Accept-Charset}i\",
    \"request_connection\":\"%{Connection}i\",
    \"request_dnt\":\"%{DNT}i\",
    \"request_forwarded\":\"%{Forwarded}i\",
    \"request_via\":\"%{Via}i\",
    \"request_cache_control\":\"%{Cache-Control}i\",
    \"request_x_requested_with\":\"%{X-Requested-With}i\",
    \"request_x_att_device_id\":\"%{X-ATT-Device-Id}i\",
    \"request_x_forwarded_for\":\"%{X-Forwarded-For}i\",
    \"status\":\"%s\",
    \"content_type\":\"%{Content-Type}o\",
    \"cache_status\":\"%{fastly_info.state}V\",
    \"is_cacheable\":%{if(fastly_info.state ~\\\"^(HIT|MISS)$\\\", \\\"true\\\", \\\"false\\\")}V,
    \"response_age\":\"%{Age}o\",
    \"response_cache_control\":\"%{Cache-Control}o\",
    \"response_expires\":\"%{Expires}o\",
    \"response_last_modified\":\"%{Last-Modified}o\",
    \"response_tsv\":\"%{TSV}o\",
    \"server_datacenter\":\"%{server.datacenter}V\",
    \"server_ip\":\"%A\",
    \"geo_city\":\"%{client.geo.city.utf8}V\",
    \"geo_country_code\":\"%{client.geo.country_code}V\",
    \"geo_continent_code\":\"%{client.geo.continent_code}V\",
    \"geo_region\":\"%{client.geo.region}V\",
    \"req_header_size\":%{req.header_bytes_read}V,
    \"req_body_size\":%{req.body_bytes_read}V,
    \"resp_header_size\":%{resp.header_bytes_written}V,
    \"resp_body_size\":%B,
    \"socket_cwnd\":%{client.socket.cwnd}V,
    \"socket_nexthop\":\"%{client.socket.nexthop}V\",
    \"socket_tcpi_rcv_mss\":%{client.socket.tcpi_rcv_mss}V,
    \"socket_tcpi_snd_mss\":%{client.socket.tcpi_snd_mss}V,
    \"socket_tcpi_rtt\":%{client.socket.tcpi_rtt}V,
    \"socket_tcpi_rttvar\":%{client.socket.tcpi_rttvar}V,
    \"socket_tcpi_rcv_rtt\":%{client.socket.tcpi_rcv_rtt}V,
    \"socket_tcpi_rcv_space\":%{client.socket.tcpi_rcv_space}V,
    \"socket_tcpi_last_data_sent\":%{client.socket.tcpi_last_data_sent}V,
    \"socket_tcpi_total_retrans\":%{client.socket.tcpi_total_retrans}V,
    \"socket_tcpi_delta_retrans\":%{client.socket.tcpi_delta_retrans}V,
    \"socket_ploss\":%{client.socket.ploss}V,
    \"backend_name\":\"%{if(req.http.x-nyt-backend,req.http.x-nyt-backend,\\\"\\\")}V\",
    \"pagetype\":\"%{if(req.http.x-nyt-route,req.http.x-nyt-route,\\\"\\\")}V\",
    \"apiversion\":\"%{if(resp.http.X-API-Version,resp.http.X-API-Version,\\\"\\\")}V\",
    \"redirect_reason\":\"%{if(req.http.var-nyt-redirect-reason,regsub(req.http.var-nyt-redirect-reason,\\\"redir=\\\\[([^\\\\]]+)\\\\]\\\",\\\"\\\\1\\\"),\\\"\\\")}V\",
    \"trace_id\": \"%{if(req.http.x-b3-trace-id,req.http.x-b3-trace-id,\\\"\\\")}V\",
    \"backend_healthy\": \"%{if(req.http.x-nyt-backend-health,req.http.x-nyt-backend-health,\\\"\\\")}V\",
    \"restarts\": %{req.restarts}V,
    \"route\": \"%{if(req.http.x-nyt-route,req.http.x-nyt-route,\\\"\\\")}V\",
    \"is_shield\": %{if(req.http.x-nyt-shield-auth,\\\"true\\\",\\\"false\\\")}V,
    \"restart_reason\":\"%{if(req.http.x-nyt-restart-reason,req.http.x-nyt-restart-reason,\\\"\\\")}V\"
    }

# sumo log integration (template data injection )
sumo_log:
  format: >-
    {
    \"service_id\":\"%{req.service_id}V\",
    \"service_version\":\"%{fastly_info.version}V\",
    \"time_start\":\"%{begin:%Y-%m-%dT%H:%M:%S%Z}t\",
    \"time_end\":\"%{end:%Y-%m-%dT%H:%M:%S%Z}t\",
    \"time_elapsed\":\"%D\",
    \"client_ip\":\"%h\",
    \"request\":\"%m\",
    \"proto_ver\":\"%H\",
    \"protocol\":\"%{if(req.http.Fastly-SSL,\\\"https\\\",\\\"http\\\")}V\",
    \"host\":\"%{Fastly-Orig-Host}i\",
    \"origin_host\":\"%v\",
    \"url\":\"%{json.escape(cstr_escape(regsub(req.url, \\\"^(.\\{0,2047\\}).*\\\", \\\"\\\\1\\\")))}V\",
    \"is_h2\":\"%{if(fastly_info.is_h2, \\\"true\\\", \\\"false\\\")}V\",
    \"request_referer\":\"%{json.escape(req.http.Referer)}V\",
    \"request_user_agent\":\"%{json.escape(regsub(req.http.User-Agent, \\\"^(.\\{0,200\\}).*\\\", \\\"\\\\1\\\"))}V\",
    \"request_accept_content\":\"%{Accept}i\",
    \"request_accept_encoding\":\"%{Accept-Encoding}i\",
    \"request_accept_charset\":\"%{Accept-Charset}i\",
    \"request_cache_control\":\"%{Cache-Control}i\",
    \"status\":\"%s\",
    \"content_type\":\"%{Content-Type}o\",
    \"cachetype\":\"%{fastly_info.state}V\",
    \"response_age\":\"%{Age}o\",
    \"response_cache_control\":\"%{Cache-Control}o\",
    \"response_expires\":\"%{Expires}o\",
    \"response_last_modified\":\"%{Last-Modified}o\",
    \"fastlydc\":\"%{server.datacenter}V\",
    \"geo_city\":\"%{client.geo.city.utf8}V\",
    \"geo_country_code\":\"%{client.geo.country_code}V\",
    \"geo_continent_code\":\"%{client.geo.continent_code}V\",
    \"geo_region\":\"%{client.geo.region}V\",
    \"req_header_size\":\"%{req.header_bytes_read}V\",
    \"req_body_size\":\"%{req.body_bytes_read}V\",
    \"resp_header_size\":\"%{resp.header_bytes_written}V\",
    \"resp_body_size\":\"%B\",
    \"backend\":\"%{if(req.http.x-nyt-backend,req.http.x-nyt-backend,\\\"\\\")}V\",
    \"pagetype\":\"%{if(resp.http.x-PageType,resp.http.x-PageType,\\\"\\\")}V\",
    \"route\":\"%{if(req.http.x-nyt-route,req.http.x-nyt-route,\\\"\\\")}V\",
    \"is_shield\":\"%{if(req.http.x-nyt-shield-auth,\\\"1\",\\\"0\")}V\",
    \"apiversion\":\"%{if(resp.http.X-API-Version,resp.http.X-API-Version,\\\"\\\")}V\",
    \"behealth\": \"%{if(req.http.x-nyt-backend-health,req.http.x-nyt-backend-health,\\\"\\\")}V\",
    \"redirect_reason\":\"%{if(req.http.x-nyt-redirect-reason,req.http.x-nyt-redirect-reason,\\\"\\\")}V\",
    \"restarts\": \"%{req.restarts}V\",
    \"restart_reason\": \"%{if(req.http.x-nyt-restart-reason,req.http.x-nyt-restart-reason,\\\"\\\")}V\",
    \"datadome_response\": \"%{if(req.http.debug-datadome-response,req.http.debug-datadome-response,\\\"\\\")}V\",
    \"mwcm_fallback\": \"%{if(req.http.x-nyt-mwcm-fallback,req.http.x-nyt-mwcm-fallback,\\\"\\\")}V\"
    }
